### ISSUE TITLE
Docker latest and master: deleting a project in admin-dashboard

### ISSUE THREAD

**Issue by AlexanderSch90** [spiral-project/ihatemoney#978]
See #977 
If i delete a project from the admin dashboard: I also get an error... 
```
Method Not Allowed
The method is not allowed for the requested URL.
```

**Comment by almet** [comment]
This seems to be related to secure cookies being enabled by default on docker. Closing as I suspect this is solved @AlexanderSch90? Let us know if not :-)

**Comment by SchoofLux** [comment]
I’m still experiencing the same issue. I cannot delete any project from the Admin dashboard.
I’m using docker which works perfectly otherwise.
Problem occurs with SESSION_COOKIE_SECURE set to True or False. No difference.
